global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'web_app_monitor'
    static_configs:
      - targets: ['metrics_exporter:8080']

  - job_name: 'web_app_monitor_active'
    scrape_interval: 10s
    metrics_path: /monitor
    static_configs:
      - targets: ['metrics_exporter:8080']

rule_files:
  - 'alert.rules'